parameters:
    eccube.twig_sandbox.allowed_tags:
        - 'autoescape'
        - 'filter'
        - 'do'
        - 'flush'
        - 'for'
        - 'set'
        - 'verbatim'
        - 'if'
        - 'spaceless'
    eccube.twig_sandbox.allowed_filters:
        - 'abs'
        - 'batch'
        - 'capitalize'
        - 'convert_encoding'
        - 'date'
        - 'date_modify'
        - 'default'
        - 'escape'
        - 'first'
        - 'format'
        - 'join'
        - 'json_encode'
        - 'keys'
        - 'last'
        - 'length'
        - 'lower'
        - 'merge'
        - 'nl2br'
        - 'number_format'
        - 'replace'
        - 'reverse'
        - 'slice'
        - 'sort'
        - 'split'
        - 'striptags'
        - 'title'
        - 'trim'
        - 'upper'
        - 'url_encode'
        - 'trans'
        - 'date_day'
        - 'date_day_with_weekday'
        - 'date_format'
        - 'date_min'
        - 'date_sec'
        - 'price'
        - 'ellipsis'
        - 'time_ago'
        - 'file_ext_icon'
        - 'no_image_product'
        - 'purify'
    eccube.twig_sandbox.allowed_functions:
        - 'attribute'
        - 'constant'
        - 'cycle'
        - 'date'
        - 'random'
        - 'range'
        - 'url'
        - 'asset'
        - 'path'
        - 'is_granted'
    eccube.twig_sandbox.allowed_methods:
        'Symfony\Bridge\Twig\AppVariable': [ 'getrequest' ]
        'Symfony\Component\HttpFoundation\Request': [ 'geturi' ]
    eccube.twig_sandbox.allowed_properties: []