eccube:
    rate_limiter:
        forgot:
            route: forgot
            method: [ 'POST' ]
            type: ip
            limit: 5
            interval: '30 minutes'
        entry:
            route: entry
            method: [ 'POST' ]
            params:
                mode: complete
            type: ip
            limit: 5
            interval: '30 minutes'
        mypage_change_ip:
            route: mypage_change
            method: [ 'POST' ]
            type: ip
            limit: 25
            interval: '30 minutes'
        mypage_change_customer:
            route: mypage_change
            method: [ 'POST' ]
            type: customer
            limit: 10
            interval: '30 minutes'
        mypage_delivery_new_ip:
            route: mypage_delivery_new
            method: [ 'POST' ]
            type: ip
            limit: 25
            interval: '30 minutes'
        mypage_delivery_edit_ip:
            route: mypage_delivery_edit
            method: [ 'POST' ]
            type: ip
            limit: 25
            interval: '30 minutes'
        mypage_delivery_delete_ip:
            route: mypage_delivery_delete
            method: [ 'DELETE' ]
            type: ip
            limit: 25
            interval: '30 minutes'
        mypage_delivery_new_customer:
            route: mypage_delivery_new
            method: [ 'POST' ]
            type: customer
            limit: 10
            interval: '30 minutes'
        mypage_delivery_edit_customer:
            route: mypage_delivery_edit
            method: [ 'POST' ]
            type: customer
            limit: 10
            interval: '30 minutes'
        mypage_delivery_delete_customer:
            route: mypage_delivery_delete
            method: [ 'DELETE' ]
            type: customer
            limit: 10
            interval: '30 minutes'
        contact:
            route: contact
            method: [ 'POST' ]
            params:
                mode: complete
            type: ip
            limit: 5
            interval: '30 minutes'
        shopping_confirm_ip:
            route: ~
            limit: 25
            interval: '30 minutes'
        shopping_confirm_customer:
            route: ~
            limit: 10
            interval: '30 minutes'
        shopping_checkout_ip:
            route: ~
            limit: 25
            interval: '30 minutes'
        shopping_checkout_customer:
            route: ~
            limit: 10
            interval: '30 minutes'
