services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    # Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~

    eccube.twig_sandbox.policy:
        class: Twig\Sandbox\SecurityPolicy
        arguments:
            $allowedTags: "%eccube.twig_sandbox.allowed_tags%"
            $allowedFilters: "%eccube.twig_sandbox.allowed_filters%"
            $allowedFunctions: "%eccube.twig_sandbox.allowed_functions%"
            $allowedMethods: "%eccube.twig_sandbox.allowed_methods%"
            $allowedProperties: "%eccube.twig_sandbox.allowed_properties%"
    eccube.twig_sandbox.extension:
        class: Twig\Extension\SandboxExtension
        arguments:
            - '@eccube.twig_sandbox.policy'
            - false
        tags: ['twig.extension']
