services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    # Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~

    eccube.twig_sandbox.policy:
        class: Twig\Sandbox\SecurityPolicy
        arguments:
            $allowedTags: "%eccube.twig_sandbox.allowed_tags%"
            $allowedFilters: "%eccube.twig_sandbox.allowed_filters%"
            $allowedFunctions: "%eccube.twig_sandbox.allowed_functions%"
    eccube.twig_sandbox.extension:
        class: Twig\Extension\SandboxExtension
        arguments:
            - '@eccube.twig_sandbox.policy'
            - false
        tags: ['twig.extension']
parameters:
    eccube.twig_sandbox.allowed_tags:
        - 'autoescape'
        - 'filter'
        - 'do'
        - 'flush'
        - 'for'
        - 'set'
        - 'verbatim'
        - 'if'
        - 'spaceless'
    eccube.twig_sandbox.allowed_filters:
        - 'abs'
        - 'batch'
        - 'capitalize'
        - 'convert_encoding'
        - 'date'
        - 'date_modify'
        - 'default'
        - 'escape'
        - 'first'
        - 'format'
        - 'join'
        - 'json_encode'
        - 'keys'
        - 'last'
        - 'length'
        - 'lower'
        - 'merge'
        - 'nl2br'
        - 'number_format'
        - 'raw'
        - 'replace'
        - 'reverse'
        - 'slice'
        - 'sort'
        - 'split'
        - 'striptags'
        - 'title'
        - 'trim'
        - 'upper'
        - 'url_encode'
        - 'trans'
    eccube.twig_sandbox.allowed_functions:
        - 'attribute'
        - 'constant'
        - 'cycle'
        - 'date'
        - 'random'
        - 'range'
        - 'url'
        - 'asset'
        - 'path'
